# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 714)
        MainWindow.setMinimumSize(QtCore.QSize(630, 714))
        MainWindow.setMaximumSize(QtCore.QSize(630, 714))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/programing.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(460, 630, 141, 51))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"  background-color: rgb(42, 42, 42);\n"
"  border-radius: 15px;\n"
"  color: #FFFFFF;\n"
"  font-size: 14px;\n"
"  line-height: normal;\n"
"  margin: 0;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(71, 71, 71);\n"
"    border:0px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 630, 141, 51))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"  background-color: rgb(42, 42, 42);\n"
"  border-radius: 15px;\n"
"  color: #FFFFFF;\n"
"  font-size: 14px;\n"
"  line-height: normal;\n"
"  margin: 0;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:rgb(71, 71, 71);\n"
"    border:0px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 170, 581, 161))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame {background: rgba(0, 0, 0, 100);}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 130, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 40, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 100, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_9.setGeometry(QtCore.QRect(290, 130, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_7.setGeometry(QtCore.QRect(290, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_8.setGeometry(QtCore.QRect(290, 100, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_5.setGeometry(QtCore.QRect(290, 10, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_6.setGeometry(QtCore.QRect(290, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"color: white")
        self.checkBox_6.setObjectName("checkBox_6")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(180, 630, 261, 51))
        self.frame_2.setStyleSheet("color:white;\n"
"background: rgba(0, 0, 0, 100);\n"
"border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(190, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:black;\n"
"padding:5px")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:black;\n"
"padding:5px")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(150, 20, 21, 16))
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 30, 581, 141))
        self.frame_3.setStyleSheet("background: rgba(0, 0, 0, 100);\n"
"color:white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 90, 75, 23))
        self.pushButton_3.setStyleSheet("QPushButton:hover{\n"
"    border:solid 2px #fff;\n"
"    background: #fff;\n"
"    color: #1f1f1f !important;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("background: rgba(0, 0, 0, 0)")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("background: rgba(0, 0, 0, 0)")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.label.setStyleSheet("background: rgba(0, 0, 0, 0)")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(290, 70, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("background: rgba(0, 0, 0, 0)")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 30, 181, 20))
        self.lineEdit_2.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 90, 181, 20))
        self.lineEdit_4.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 90, 181, 21))
        self.lineEdit_3.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(200, 30, 75, 23))
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"    border:solid 2px #fff;\n"
"    background: #fff;\n"
"    color: #1f1f1f !important;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 90, 75, 23))
        self.pushButton_4.setStyleSheet("QPushButton:hover{\n"
"    border:solid 2px #fff;\n"
"    background: #fff;\n"
"    color: #1f1f1f !important;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 30, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton{    \n"
"    border:solid 2px #fff;\n"
"    background: transparent;\n"
"    color: #fff !important;}\n"
"QPushButton:hover{\n"
"    border:solid 2px #fff;\n"
"    background: #fff;\n"
"    color: #1f1f1f !important;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.lineEdit.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(300, 330, 301, 111))
        self.frame_4.setStyleSheet("background: rgba(0, 0, 0, 100);\n"
"border-radius: 0px 0px 20px 20px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 10, 281, 20))
        self.lineEdit_5.setTabletTracking(False)
        self.lineEdit_5.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 40, 281, 20))
        self.lineEdit_6.setTabletTracking(False)
        self.lineEdit_6.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setDragEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 70, 281, 20))
        self.lineEdit_7.setTabletTracking(False)
        self.lineEdit_7.setStyleSheet("color:white;\n"
"border:1px solid white;\n"
"background: rgba(0, 0, 0, 200)")
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setDragEnabled(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(-1230, -10, 1881, 731))
        self.label_8.setStyleSheet("")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/newPrefix/back1.jpg"))
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timming"))
        self.pushButton_5.setText(_translate("MainWindow", "Начать"))
        self.pushButton_6.setText(_translate("MainWindow", "Настройка"))
        self.checkBox.setText(_translate("MainWindow", "Сплит"))
        self.checkBox_10.setText(_translate("MainWindow", "Добавить название релиза"))
        self.checkBox_2.setText(_translate("MainWindow", "Нормализация дорог"))
        self.checkBox_4.setText(_translate("MainWindow", "Поднятие громкости дабберов +1.5"))
        self.checkBox_3.setText(_translate("MainWindow", "Нормализация видео"))
        self.checkBox_9.setText(_translate("MainWindow", "Создание подпапки для проекта"))
        self.checkBox_7.setText(_translate("MainWindow", "Рендер аудио (сразу)"))
        self.checkBox_8.setText(_translate("MainWindow", "Рендер видео (сразу)"))
        self.checkBox_5.setText(_translate("MainWindow", "Добавление субтитров Item"))
        self.checkBox_6.setText(_translate("MainWindow", "Добавление субтитров Region"))
        self.label_7.setText(_translate("MainWindow", "KOT3"))
        self.label_6.setText(_translate("MainWindow", "Dooby Duglas"))
        self.label_5.setText(_translate("MainWindow", "and"))
        self.pushButton_3.setText(_translate("MainWindow", "Выбрать"))
        self.label_2.setText(_translate("MainWindow", "Путь к шаблону проекта"))
        self.label_3.setText(_translate("MainWindow", "Путь к Reaper"))
        self.label.setText(_translate("MainWindow", "Путь к FXChain (пресеты)"))
        self.label_4.setText(_translate("MainWindow", "Путь к папки серии"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.pushButton_4.setText(_translate("MainWindow", "Выбрать"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбрать"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Задержка при открытии (def = 1s)"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Задержка при сохранении (def = 1s)"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Задержка при добавлении FX (def = 0.5s)"))
import resursec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
